---
- hosts: all
  become_method: sudo
  become: yes

  vars:
    mount_dir: /vol/data

  tasks:
    - name: install libgmp10
      apt:  update_cache=yes upgrade=full

    - name: install libgmp10
      apt: name=libgmp10

    - name: install python-pycurl
      apt: name=python-pycurl

    - name: install cloud-utils
      apt: name=cloud-utils

#    - name: format new volume
#      filesystem: fstype=ext4 dev=/dev/xvdb
#
#    - name: edit fstab and mount the vol
#      action: mount name={{mount_dir}} src=/dev/xvdb opts=noatime fstype=ext4 state=mounted
#
#    - name: initialize swap
#      shell: mkswap /dev/xvdc
#
#    - name: add swap to fstab
#      shell: echo "/dv/xvdc swap                 swap       defaults              0 0" >> /etc/fstab
#    
    - name: add arangodb key
      apt_key:
        url=https://www.arangodb.com/repositories/{{arangodb_repo}}/xUbuntu_16.04/Release.key
        state=present
        validate_certs=no

    - name: add arangodb repo
      apt_repository:
        repo='deb https://www.arangodb.com/repositories/{{arangodb_repo}}/xUbuntu_16.04 /'
        state=present

    - name: install arangodb
      apt: name={{arangodb_name}}={{arangodb_version}} update_cache=yes

    - name: create a local arangod config file
      template: src=templates/{{arangodb_name}}/arangod.conf.local.j2 dest=/etc/{{arangodb_name}}/arangod.conf.local

    - name: create a local arangosh config file
      template: src=templates/{{arangodb_name}}/arangosh.conf.local.j2 dest=/etc/{{arangodb_name}}/arangosh.conf.local

    - name: create a cloud init file
      copy:
        src: templates/rc.local
        dest: /var/lib/cloud/scripts/per-boot/mountfiles
        mode: 0744

    - name: ensure arangodb is running
      service: name={{arangodb_name}} state=stopped

    - name: delete arangodb temporay standalone folder
      file: path=/var/lib/{{arangodb_name}} state=absent

    - name: patch startup script to use default password
      lineinfile:
        dest=/etc/init.d/{{arangodb_name}}
        insertafter="^PIDFILE="
        regexp="^export ARANGODB_DEFAULT_ROOT_PASSWORD="
        line="export ARANGODB_DEFAULT_ROOT_PASSWORD=$(ec2metadata --instance-id)"
        state=present

    - name: patch datadir in startup script
      lineinfile:
        dest=/etc/init.d/{{arangodb_name}}
        regexp=" cd /var/lib/{{arangodb_name}} "
        line="    ( cd {{mount_dir}}/standalone && chown -R arangodb:arangodb . ) || exit 1"
        state=present

    # cannot use replace (avaiable from 1.6 onwards only)
    - name: patch startup script
      shell: sed -e 's:-c \$CONF::' < /etc/init.d/{{arangodb_name}} > /etc/init.d/{{arangodb_name}}.new && mv /etc/init.d/{{arangodb_name}}.new /etc/init.d/{{arangodb_name}} && chmod 755 /etc/init.d/{{arangodb_name}}

#    - name: create arangodb final standalone folder
#      file: path={{mount_dir}}/standalone state=directory owner=arangodb group=arangodb

    - name: Remove authorized keys from user ubuntu
      command: rm /home/ubuntu/.ssh/authorized_keys

    - name: Remove authorized keys from user root
      command: rm /root/.ssh/authorized_keys

    - name: remove cache files and logs
      command: rm -f /var/cache/apt/archives/*deb /var/log/*