---
- hosts: all
  sudo: yes

  vars:
    mount_dir: /vol/data

  tasks:
    - name: install libgmp10
      apt: name=libgmp10

    - name: install python-pycurl
      apt: name=python-pycurl

    - name: install cloud-utils
      apt: name=cloud-utils

    - name: format new volume
      filesystem: fstype=ext4 dev=/dev/xvde

    - name: edit fstab and mount the vol
      action: mount name={{mount_dir}} src=/dev/xvde opts=noatime fstype=ext4 state=mounted

    - name: add arangodb key
      apt_key:
        url=https://www.arangodb.com/repositories/arangodb2/xUbuntu_14.04/Release.key
        state=present
        validate_certs=no

    - name: add arangodb repo
      apt_repository:
        repo='deb https://www.arangodb.com/repositories/arangodb2/xUbuntu_14.04 /'
        state=present

    - name: install arangodb
      apt: name=arangodb={{arangodb_version}} update_cache=yes

    - name: create a local arangod config file
      template: src=templates/arangod.conf.local.j2 dest=/etc/arangodb/arangod.conf.local

    - name: create a local arangosh config file
      template: src=templates/arangosh.conf.local.j2 dest=/etc/arangodb/arangosh.conf.local

    - name: ensure arangodb is running
      service: name=arangodb state=stopped

    - name: delete arangodb temporay standalone folder
      file: path=/var/lib/arangodb state=absent

    - name: patch startup script to use default password
      lineinfile:
        dest=/etc/init.d/arangodb
        insertafter="^CONF="
        regexp="^export ARANGODB_DEFAULT_ROOT_PASSWORD="
        line="export ARANGODB_DEFAULT_ROOT_PASSWORD=$(ec2metadata --instance-id)"
        state=present

    - name: patch datadir in startup script
      lineinfile:
        dest=/etc/init.d/arangodb
        regexp=" cd /var/lib/arangodb "
        line="    ( cd {{mount_dir}}/standalone && chown -R arangodb:arangodb . ) || exit 1"
        state=present

    # cannot use replace (avaiable from 1.6 onwards only)
    - name: patch startup script
      shell: sed -e 's:-c \$CONF::' < /etc/init.d/arangodb > /etc/init.d/arangodb.new && mv /etc/init.d/arangodb.new /etc/init.d/arangodb && chmod 755 /etc/init.d/arangodb

    - name: create arangodb final standalone folder
      file: path={{mount_dir}}/standalone state=directory owner=arangodb group=arangodb

    - name: Remove authorized keys from user ubuntu
      command: rm /home/ubuntu/.ssh/authorized_keys

    - name: Remove authorized keys from user root
      command: rm /root/.ssh/authorized_keys
